@baseUrl = http://localhost:3000
@contentType = application/json
@authToken =

@productId = 


### Get all products
GET {{baseUrl}}/products

### Search products
GET {{baseUrl}}/products?search=brake

### Get single product
GET {{baseUrl}}/products/{{productId}}



### Create product with multiple images
POST {{baseUrl}}/products
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

Brembo 4-Port Racing Pads
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="description"

Brembo 4-Port Racing Pads deliver unmatched stopping power and heat resistance for high-performance driving and track conditions. Engineered for precision and durability, they ensure consistent braking performance under extreme stress.
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

12400
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

30
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image1.jpg"
Content-Type: image/jpeg

< /home/m_/Pictures/brake1.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image2.jpg"
Content-Type: image/jpeg

< /home/m_/Pictures/brake2.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image3.jpg"
Content-Type: image/jpeg

< /home/m_/Pictures/brake3.jpg

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="images"; filename="image4.jpg"
Content-Type: image/jpeg

< /home/m_/Pictures/brake4.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Update product (admin only)
PUT {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="name"

Brembo 4-Port Racing Pads
------WebKitFormBoundary
Content-Disposition: form-data; name="price"

74499.99

------WebKitFormBoundary
Content-Disposition: form-data; name="stock"

13
------WebKitFormBoundary--

### Delete product (admin only)
DELETE {{baseUrl}}/products/{{productId}}
Authorization: Bearer {{authToken}}


