@baseUrl = http://localhost:3000
@contentType = application/json
@authToken =  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ZWY3OTkzNS03OWQ5LTQ4NDItOWMxNS01ZWViMTQxMzg0ZDQiLCJlbWFpbCI6Im1hcmtuZHdpZ2FAZ21haWwuY29tIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzUwNDEzNjU3LCJleHAiOjE3NTA1MDAwNTd9.ZT_2k5qp5ZMdegXxDB3SmRNX_uhPYt4jbbROZtlf0OI

@userId = 00ab177c-6097-4a0b-9745-46476da947f5

### Get all users
GET {{baseUrl}}/users
Authorization: Bearer {{authToken}}


### Get user profile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{authToken}}

### Update user profile 
PUT {{baseUrl}}/users/profile
Authorization: Bearer {{authToken}}
Content-Type: {{contentType}}

{
    "firstName": "Markide",
    "lastName": "Shopper",
    "password": "Npass_123"
}


### Upload Profile Image
PUT {{baseUrl}}/users/profile
Authorization: Bearer {{authToken}}
Content-Type: multipart/form-data; boundary=----FormBoundary1234

------FormBoundary1234
Content-Disposition: form-data; name="profileImage"; filename="profile.jpg"
Content-Type: image/jpeg

< /home/m_/Pictures/profile.jpg
------FormBoundary1234--


### Deactivate own account 
DELETE {{baseUrl}}/users/deactivate
Authorization: Bearer {{authToken}}


### Delete inactive user 
DELETE {{baseUrl}}/users/{{userId}}
Authorization: Bearer {{authToken}}
